import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Nav/Nav";
import Footer from "../components/Footer/Footer";
import { AuthProvider } from "../Context/AuthContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          
          >
          <AuthProvider>
          <div>
            <div className="w-full fixed top-0 left-0 text-white shadow-md z-10">
              <Navbar />
            </div>

          {children}
            <div className="w-full fixed  bottom-0 ">
              <Footer />
            </div>
          </div>
      </AuthProvider>
        </body>
    </html>
  );
}
